\hypertarget{classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_reasoner_internal_exception}{\section{org.\-semanticweb.\-owlapi.\-reasoner.\-Reasoner\-Internal\-Exception Class Reference}
\label{classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_reasoner_internal_exception}\index{org.\-semanticweb.\-owlapi.\-reasoner.\-Reasoner\-Internal\-Exception@{org.\-semanticweb.\-owlapi.\-reasoner.\-Reasoner\-Internal\-Exception}}
}
Inheritance diagram for org.\-semanticweb.\-owlapi.\-reasoner.\-Reasoner\-Internal\-Exception\-:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=4.000000cm]{classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_reasoner_internal_exception}
\end{center}
\end{figure}
\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\hyperlink{classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_reasoner_internal_exception_a94adcecf0c1788f5abdee5672cf8be83}{Reasoner\-Internal\-Exception} (Throwable cause)
\item 
\hyperlink{classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_reasoner_internal_exception_a8d52b4cecb5a732ceae21eec2fb02576}{Reasoner\-Internal\-Exception} (String message)
\item 
\hyperlink{classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_reasoner_internal_exception_ae44b6c331d81bda7770249632288f9b5}{Reasoner\-Internal\-Exception} (String message, Throwable cause)
\end{DoxyCompactItemize}
\subsection*{Static Private Attributes}
\begin{DoxyCompactItemize}
\item 
static final long \hyperlink{classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_reasoner_internal_exception_a284458fbe85b23f3709bb11cdf366692}{serial\-Version\-U\-I\-D} = 30406\-L
\end{DoxyCompactItemize}


\subsection{Detailed Description}
Author\-: Matthew Horridge\par
 The University of Manchester\par
 Bio-\/\-Health Informatics Group\par
 Date\-: 05-\/\-Jul-\/2010 

Specifies that a some internal error occurred during reasoning. Each reasoner implementation will specify the cause of the error in the message. 

This exception is only thrown when an internal error (due to errors in the reasoner code) has occurred and the reasoner cannot recover silently from the error. If the reasoner can recover silently this exception will not be thrown. 

Clients should dispose of the reasoner when an internal reasoner exception is thrown because the error is unrecoverable and the internal state of the reasoner may be corrupt. 

\subsection{Constructor \& Destructor Documentation}
\hypertarget{classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_reasoner_internal_exception_a94adcecf0c1788f5abdee5672cf8be83}{\index{org\-::semanticweb\-::owlapi\-::reasoner\-::\-Reasoner\-Internal\-Exception@{org\-::semanticweb\-::owlapi\-::reasoner\-::\-Reasoner\-Internal\-Exception}!Reasoner\-Internal\-Exception@{Reasoner\-Internal\-Exception}}
\index{Reasoner\-Internal\-Exception@{Reasoner\-Internal\-Exception}!org::semanticweb::owlapi::reasoner::ReasonerInternalException@{org\-::semanticweb\-::owlapi\-::reasoner\-::\-Reasoner\-Internal\-Exception}}
\subsubsection[{Reasoner\-Internal\-Exception}]{\setlength{\rightskip}{0pt plus 5cm}org.\-semanticweb.\-owlapi.\-reasoner.\-Reasoner\-Internal\-Exception.\-Reasoner\-Internal\-Exception (
\begin{DoxyParamCaption}
\item[{Throwable}]{cause}
\end{DoxyParamCaption}
)}}\label{classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_reasoner_internal_exception_a94adcecf0c1788f5abdee5672cf8be83}
\hypertarget{classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_reasoner_internal_exception_a8d52b4cecb5a732ceae21eec2fb02576}{\index{org\-::semanticweb\-::owlapi\-::reasoner\-::\-Reasoner\-Internal\-Exception@{org\-::semanticweb\-::owlapi\-::reasoner\-::\-Reasoner\-Internal\-Exception}!Reasoner\-Internal\-Exception@{Reasoner\-Internal\-Exception}}
\index{Reasoner\-Internal\-Exception@{Reasoner\-Internal\-Exception}!org::semanticweb::owlapi::reasoner::ReasonerInternalException@{org\-::semanticweb\-::owlapi\-::reasoner\-::\-Reasoner\-Internal\-Exception}}
\subsubsection[{Reasoner\-Internal\-Exception}]{\setlength{\rightskip}{0pt plus 5cm}org.\-semanticweb.\-owlapi.\-reasoner.\-Reasoner\-Internal\-Exception.\-Reasoner\-Internal\-Exception (
\begin{DoxyParamCaption}
\item[{String}]{message}
\end{DoxyParamCaption}
)}}\label{classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_reasoner_internal_exception_a8d52b4cecb5a732ceae21eec2fb02576}
\hypertarget{classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_reasoner_internal_exception_ae44b6c331d81bda7770249632288f9b5}{\index{org\-::semanticweb\-::owlapi\-::reasoner\-::\-Reasoner\-Internal\-Exception@{org\-::semanticweb\-::owlapi\-::reasoner\-::\-Reasoner\-Internal\-Exception}!Reasoner\-Internal\-Exception@{Reasoner\-Internal\-Exception}}
\index{Reasoner\-Internal\-Exception@{Reasoner\-Internal\-Exception}!org::semanticweb::owlapi::reasoner::ReasonerInternalException@{org\-::semanticweb\-::owlapi\-::reasoner\-::\-Reasoner\-Internal\-Exception}}
\subsubsection[{Reasoner\-Internal\-Exception}]{\setlength{\rightskip}{0pt plus 5cm}org.\-semanticweb.\-owlapi.\-reasoner.\-Reasoner\-Internal\-Exception.\-Reasoner\-Internal\-Exception (
\begin{DoxyParamCaption}
\item[{String}]{message, }
\item[{Throwable}]{cause}
\end{DoxyParamCaption}
)}}\label{classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_reasoner_internal_exception_ae44b6c331d81bda7770249632288f9b5}


\subsection{Member Data Documentation}
\hypertarget{classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_reasoner_internal_exception_a284458fbe85b23f3709bb11cdf366692}{\index{org\-::semanticweb\-::owlapi\-::reasoner\-::\-Reasoner\-Internal\-Exception@{org\-::semanticweb\-::owlapi\-::reasoner\-::\-Reasoner\-Internal\-Exception}!serial\-Version\-U\-I\-D@{serial\-Version\-U\-I\-D}}
\index{serial\-Version\-U\-I\-D@{serial\-Version\-U\-I\-D}!org::semanticweb::owlapi::reasoner::ReasonerInternalException@{org\-::semanticweb\-::owlapi\-::reasoner\-::\-Reasoner\-Internal\-Exception}}
\subsubsection[{serial\-Version\-U\-I\-D}]{\setlength{\rightskip}{0pt plus 5cm}final long org.\-semanticweb.\-owlapi.\-reasoner.\-Reasoner\-Internal\-Exception.\-serial\-Version\-U\-I\-D = 30406\-L\hspace{0.3cm}{\ttfamily [static]}, {\ttfamily [private]}}}\label{classorg_1_1semanticweb_1_1owlapi_1_1reasoner_1_1_reasoner_internal_exception_a284458fbe85b23f3709bb11cdf366692}


The documentation for this class was generated from the following file\-:\begin{DoxyCompactItemize}
\item 
api/src/main/java/org/semanticweb/owlapi/reasoner/\hyperlink{_reasoner_internal_exception_8java}{Reasoner\-Internal\-Exception.\-java}\end{DoxyCompactItemize}
